site_name: ASGA

nav:
  - Home: index.md
  
  - Documentation:
    - Installation: Install.md
    - Global Use Funcitons: Global_Fun.md
    - GUI Use Functions: GUI_Fun.md
    - Pre Analysis Functions: Pre_anal.md
    - KMTs Analysis Functions: KMT_anal.md
    - SMTs Analysis Functions: SMT_anal.md
    - Test Unit: Test.md
    
  - About: 
      - License: license.md
      - Release Note: Change_Log.md
      - Citation: Cit.md

theme: readthedocs
repo_url: https://github.com/RRobert92/ASGA
site_url: https://kiewisz.shinyapps.io/ASGA/
edit_uri: /RRobert92/ASGA/blob/main/docs/docs/
plugins:
  - search:
      lang: en
      prebuild_index: python
  - macros

extra:
  version: 0.33
  Data: 28.12.2020
  Author: Robert kiewisz
  License: GPL V3.0